In [1]:
import pandas as pd

df = pd.read_csv("housing.csv")


print("Dataset Information:")
df.info()


print("Statistical Information (Numerical Columns):")
print(df.describe())


print("Unique label counts for Ocean Proximity:")
print(df["ocean_proximity"].value_counts())


print("Columns with missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

FileNotFoundError: [Errno 2] No such file or directory: 'housing.csv'

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Diabetes Dataset.zip to Diabetes Dataset (1).zip

In [7]:
import os
os.listdir()

['.config', 'Diabetes Dataset (1).zip', 'Diabetes Dataset.zip', 'sample_data']

In [8]:
from google.colab import files
uploaded = files.upload()

Saving Diabetes Dataset.csv to Diabetes Dataset.csv

In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv("Diabetes Dataset.csv")
df.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

In [11]:

numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Fill missing values ONLY for numerical columns
df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].mean())

# Verify
df.isnull().sum()

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

In [13]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

df = df[~((df < (Q1 - 1.5 * IQR)) |
          (df > (Q3 + 1.5 * IQR))).any(axis=1)]

In [14]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
df_minmax = pd.DataFrame(minmax.fit_transform(df), columns=df.columns)
df_minmax.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,0.892231,0.452186,0.5,0.193548,0.328947,0.690476,0.230769,0.694915,0.723404,0.2,0.673469,0.761905,0.15,0.0
1,0.106516,0.316206,0.0,0.354839,0.381579,0.404762,0.900000,0.406780,0.361702,0.4,0.387755,0.380952,0.50,0.0
2,0.286967,0.188926,0.0,0.354839,0.381579,0.404762,0.900000,0.406780,0.361702,0.4,0.387755,0.380952,0.50,0.0
3,0.630326,0.303545,0.0,0.290323,0.381579,0.190476,0.346154,0.406780,0.425532,0.6,0.326531,0.428571,0.20,0.0
4,0.006266,0.452318,0.0,0.225806,0.250000,0.440476,0.238462,0.627119,0.744681,0.6,0.448980,0.761905,0.25,0.0

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_standard = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
df_standard.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,1.634136,0.322377,0.947475,-2.344564,-0.661056,1.293338,-1.688590,1.126537,1.485468,-1.284433,1.348145,1.482732,-2.141359,0.0
1,-1.060798,-0.421699,-1.040434,-1.280766,-0.395535,-0.104775,2.040328,-0.410418,-0.195241,-0.352859,-0.059949,-0.268049,-0.394447,0.0
2,-0.441866,-1.118165,-1.040434,-1.280766,-0.395535,-0.104775,2.040328,-0.410418,-0.195241,-0.352859,-0.059949,-0.268049,-0.394447,0.0
3,0.735825,-0.490976,-1.040434,-1.706285,-0.395535,-1.153359,-1.045673,-0.410418,0.101355,0.578715,-0.361683,-0.049201,-1.891800,0.0
4,-1.404650,0.323102,-1.040434,-2.131805,-1.059337,0.069989,-1.645729,0.764900,1.584333,0.578715,0.241786,1.482732,-1.642241,0.0

In [16]:
from google.colab import files
uploaded = files.upload()

Saving adult.csv.csv to adult.csv.csv

In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler

df = pd.read_csv("adult.csv.csv")


numerical_cols = df.select_dtypes(include=['int64','float64']).columns
df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].mean())


le = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])


Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df = df[~((df < (Q1 - 1.5 * IQR)) |
          (df > (Q3 + 1.5 * IQR))).any(axis=1)]




minmax = MinMaxScaler()
df_minmax = pd.DataFrame(minmax.fit_transform(df), columns=df.columns)


scaler = StandardScaler()
df_standard = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

#results
print(df.head())
print(df_minmax.head())
print(df_standard.head())

    age  workclass  fnlwgt  education  educational-num  marital-status  \
1    38          4   89814         11                9               2
8    24          4  369667         15               10               4
12   26          4   82091         11                9               4
24   25          4  205947          9               13               2
28   54          4   99516         11                9               2

    occupation  relationship  race  gender  capital-gain  capital-loss  \
1            5             0     4       1             0             0
8            8             4     4       0             0             0
12           1             1     4       0             0             0
24          10             0     4       1             0             0
28           3             0     4       1             0             0

    hours-per-week  native-country  income
1               50              39       0
8               40              39       0
12              39              39       0
24              40              39       0
28              35              39       0
        age  workclass    fnlwgt  education  educational-num  marital-status  \
0  0.344262        0.0  0.188277   0.555556         0.363636        0.333333
1  0.114754        0.0  0.881156   1.000000         0.454545        0.666667
2  0.147541        0.0  0.169156   0.555556         0.363636        0.666667
3  0.131148        0.0  0.475807   0.333333         0.727273        0.333333
4  0.606557        0.0  0.212298   0.555556         0.363636        0.333333

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0    0.307692           0.0   0.0     1.0           0.0           0.0
1    0.538462           0.8   0.0     0.0           0.0           0.0
2    0.000000           0.2   0.0     0.0           0.0           0.0
3    0.692308           0.0   0.0     1.0           0.0           0.0
4    0.153846           0.0   0.0     1.0           0.0           0.0

   hours-per-week  native-country  income
0        0.894737             0.0     0.0
1        0.368421             0.0     0.0
2        0.315789             0.0     0.0
3        0.368421             0.0     0.0
4        0.105263             0.0     0.0
        age  workclass    fnlwgt  education  educational-num  marital-status  \
0  0.226963        0.0 -1.025098  -0.133500        -0.656382       -0.378235
1 -0.987430        0.0  2.240250   1.491131        -0.074960        0.845925
2 -0.813945        0.0 -1.115210  -0.133500        -0.656382        0.845925
3 -0.900688        0.0  0.329952  -0.945815         1.669304       -0.378235
4  1.614840        0.0 -0.911894  -0.133500        -0.656382       -0.378235

   occupation  relationship  race    gender  capital-gain  capital-loss  \
0   -0.368887     -1.028367   0.0  0.767845           0.0           0.0
1    0.350187      1.647081   0.0 -1.302347           0.0           0.0
2   -1.327652     -0.359505   0.0 -1.302347           0.0           0.0
3    0.829570     -1.028367   0.0  0.767845           0.0           0.0
4   -0.848269     -1.028367   0.0  0.767845           0.0           0.0

   hours-per-week  native-country  income
0        2.286096             0.0     0.0
1       -0.341340             0.0     0.0
2       -0.604084             0.0     0.0
3       -0.341340             0.0     0.0
4       -1.655058             0.0     0.0